apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
  - name: tools
    image: phongdosw2/tools
    command: ["sleep", "3600"]
    resources: 
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
