apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: app-svc-2
spec:
  containers:
  - name: nginx-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: app-svc-2
spec:
  containers:
  - name: httpd-pod
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80