apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: express-app-deployment
spec:
  maxReplicas: 8
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app-deployment
