apiVersion: v1
kind: Pod
metadata:
  name: "express-app-1-2"
  namespace: default
  labels:
    app: "express-app-1-2"
spec:
  volumes:
    - name: "myvol"
      hostPath:
          path: "/home/docker/html"
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: 150M
        cpu: 100m
      requests:
        memory: 150M
        cpu: 100m
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: "myvol"
  - name: express-app-1
    image: phongdosw2/express-app-1
    resources:
      limits:
        cpu: 100m
        memory: 150M
      requests:
        cpu: 100m
        memory: 150M
    ports:
    - containerPort:  3301
  - name: express-app-2
    image: phongdosw2/express-app-2
    resources:
      limits:
        cpu: 100m
        memory: 150M
      requests:
        cpu: 100m
        memory: 150M
    ports:
    - containerPort:  3302
  restartPolicy: Always