# Base image for Node.js application
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy remaining application files
COPY . .

# Expose port for your application (adjust if needed)
EXPOSE 3302

# Start the application
CMD [ "npm", "start" ]
