apiVersion: v1
kind: Pod
metadata:
  name: "express-app-1"
  namespace: default
  labels:
    app: "express-app"
spec:
  containers:
  - name: express-app-1
    image: phongdosw2/express-app-1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  3301
  restartPolicy: Always